apiVersion: v1
kind: Service
metadata:
  name: eos-master
spec:
  selector:
    app: eos
  type: ClusterIP
  ports:
  - name: nodeos
    protocol: TCP
    port: 8888
    targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eos
  template:
    metadata:
      labels:
        app: eos
    spec:
      containers:
      - name: eos 
        image: consensusclubs/eos-dev:v1.0.0
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "-c", "--" ]
        args:
          - ./setup.sh;
            while true; do sleep 30; done;
        ports:
        - containerPort: 8888 
