apiVersion: v1
kind: Service
metadata:
  name: nodejs-master
spec:
  selector:
    app: nodejs
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31000
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nodejs-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: consensusclubs/api-consensus-clubs:v1.0.0 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "node /app/index.js" ]
        env:
        - name: TWITTER_CALLBACK_URL
          valueFrom:
            secretKeyRef:
              name: node-secrets
              key: twitterCallbackUrl
        - name: TWITTER_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              name: node-secrets
              key: twitterConsumerKey
        - name: TWITTER_CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              name: node-secrets
              key: twitterConsumerSecret
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: node-secrets
              key: sessionSecret
        - name: POSTGRES_DB_NAME
          valueFrom:
            secretKeyRef:
              name: node-secrets
              key: postgresDbName
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: node-secrets
              key: postgresUser
        - name: POSTGRES_PASS
          valueFrom:
            secretKeyRef:
              name: node-secrets
              key: postgresPass
