apiVersion: v1
kind: Service
metadata:
  name: postgres-master
spec:
  selector:
    app: postgres
  type: ClusterIP 
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432 
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: postgres-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:10.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: postgresDbName
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: postgresUser
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: postgresPassword
